import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :pears, PearsWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Email delivery is intentionally disabled in production until a real
# provider is wired up: the mailer still uses Swoosh.Adapters.Local, and
# with local storage disabled below, any Mailer.deliver call exits.
# Registration auto-confirms teams and password reset is unavailable, so
# nothing should attempt to send email.

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Pears.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :pears, Pears.Scheduler,
  jobs: [
    # Every hour on the hour from Monday through Friday.
    {"0 * * * 1-5", {Pears, :send_hand_off_reminders, []}}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
